(function(){
  var meals=[
    {icon:'🥤',name:'Desayuno',desc:'Whey + frutos secos + leche 0%',kcal:330,slot:'desayuno',variant:'quick_1'},
    {icon:'🍳',name:'Almuerzo',desc:'Claras + huevo + fresas',kcal:169,slot:'almuerzo',variant:'quick_2'},
    {icon:'🍗',name:'Comida',desc:'Pollo + verdura verde',kcal:239,slot:'comida',variant:'quick_3'},
    {icon:'🥛',name:'Merienda',desc:'Yogur + Whey + frutos secos',kcal:326,slot:'merienda',variant:'quick_4'},
    {icon:'🌙',name:'Cena',desc:'Pollo + verdura verde',kcal:239,slot:'cena',variant:'quick_5'},
    {icon:'🍍',name:'Post-entreno',desc:'150 g de piña',kcal:87,slot:'post-entreno',variant:'quick_6'},
    {icon:'🫐',name:'Postre',desc:'Queso batido + arándanos',kcal:118,slot:'postre',variant:'quick_7'}
  ];
  var mealInfo={'ayunas':['🌅','Ayunas'],'desayuno':['🍳','Desayuno'],'almuerzo':['🥪','Almuerzo'],'comida':['🍽️','Comida'],'merienda':['🥛','Merienda'],'post-entreno':['🍍','Post-entreno'],'cena':['🌙','Cena'],'postre':['🍓','Postre'],'snacks':['🍫','Snacks'],'salsas':['🥫','Salsas'],'antes de dormir':['💊','Antes de dormir']};
  function telegram(){try{return window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null}catch(e){return null}}
  function initData(){var tg=telegram();try{return tg&&tg.initData?tg.initData:''}catch(e){return ''}}
  function haptic(type){var tg=telegram();try{if(tg&&tg.HapticFeedback){tg.HapticFeedback.impactOccurred(type||'light')}}catch(e){}}
  function alertMessage(text){var tg=telegram();try{if(tg&&tg.showAlert){tg.showAlert(text);return}}catch(e){}window.alert(text)}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function num(v){var n=Number(v||0);return isFinite(n)?n:0}
  function fmt(v,d){return num(v).toLocaleString('es-ES',{maximumFractionDigits:d==null?1:d})}
  function request(action,payload){return fetch(window.location.href,{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':initData()},body:JSON.stringify({action:action,payload:payload||{}})}).then(function(r){return r.text().then(function(t){var j;try{j=JSON.parse(t)}catch(e){throw new Error('Respuesta no válida')}if(!r.ok||!j.ok){throw new Error(j.reason||j.error||('HTTP '+r.status))}return j.data})})}
  function isDietClosed(diet){var pill=diet?diet.querySelector('.hero .pill'):null;return !!(pill&&String(pill.textContent||'').toLowerCase().indexOf('cerrada')>=0)}
  function buttonHtml(m,i,disabled){return '<button class="quickMealBtn" data-quick="'+i+'" '+(disabled?'disabled':'')+'><div class="quickMealTop"><span class="quickMealIcon">'+m.icon+'</span><span class="quickMealKcal">'+m.kcal+' kcal</span></div><div><div class="quickMealName">'+m.name+'</div><div class="quickMealDesc">'+m.desc+'</div></div></button>'}
  function totals(foods){var out={};for(var i=0;i<foods.length;i++){var slot=String(foods[i].meal_slot||'otros');if(!out[slot]){out[slot]={count:0,kcal:0}}out[slot].count++;out[slot].kcal+=num(foods[i].calories)}return out}
  function consumedCard(root,foods){var heads=root.querySelectorAll('.sectionhead'),target=null;for(var i=0;i<heads.length;i++){var t=heads[i].querySelector('.sectiontitle');if(t&&String(t.textContent||'').toLowerCase().indexOf('consumido hoy')>=0){target=heads[i];break}}if(!target){return}var card=target.nextElementSibling;if(!card||String(card.className).indexOf('card')<0){return}var html='';if(!foods.length){html='<div class="empty">Todavía no hay alimentos registrados.</div>'}for(var j=0;j<foods.length;j++){var slot=String(foods[j].meal_slot||''),info=mealInfo[slot]||['🍴',slot];html+='<div class="foodrow"><div class="row"><div><div class="foodname">'+esc(foods[j].product_name||'')+'</div><div class="foodmeta">'+info[0]+' '+esc(info[1])+' · '+fmt(foods[j].quantity,1)+' '+esc(foods[j].unit||'')+'</div></div><span class="pill">'+Math.round(num(foods[j].calories))+' kcal</span></div></div>'}card.innerHTML=html;var meta=target.querySelector('.sectionmeta');if(meta){meta.textContent=foods.length+' elementos'}}
  function patchDietView(d){var root=document.getElementById('diet');if(!root||!d){return}var s=d.session||{},foods=d.foods||[],hero=root.querySelector('.hero'),t=totals(foods);if(hero){var big=hero.querySelector('.big');if(big){big.innerHTML=Math.round(num(s.calories_total))+' <span class="unit">kcal</span>'}var small=hero.querySelector('.small');if(small){small.textContent=foods.length+' registros hoy · '+fmt(s.protein_g,1)+' g proteína'}}var cards=root.querySelectorAll('[data-slot]');for(var i=0;i<cards.length;i++){var slot=String(cards[i].getAttribute('data-slot')||''),x=t[slot]||{count:0,kcal:0},pill=cards[i].querySelector('.pill'),meta=cards[i].querySelector('.mealmeta'),kcal=cards[i].querySelector('.mealKcal');if(pill){pill.textContent=String(x.count)}if(meta){meta.textContent=x.count?x.count+' registro'+(x.count===1?'':'s'):'Ver opciones'}if(kcal){kcal.textContent=Math.round(x.kcal)+' kcal'}}consumedCard(root,foods)}
  function ensureQuickMeals(){var diet=document.getElementById('diet');if(!diet||document.getElementById('quickMealsWrap')){return}var hero=diet.querySelector('.hero');if(!hero){return}var closed=isDietClosed(diet),wrap=document.createElement('div'),html='';wrap.id='quickMealsWrap';wrap.className='quickMealsWrap';html+='<div class="quickMealsHead"><div class="sectiontitle">⚡ Comidas rápidas</div><div class="sectionmeta">Registro en un toque</div></div>';html+='<div class="quickMealsGrid">';for(var i=0;i<meals.length;i++){html+=buttonHtml(meals[i],i,closed)}html+='</div>';wrap.innerHTML=html;if(hero.nextSibling){hero.parentNode.insertBefore(wrap,hero.nextSibling)}else{hero.parentNode.appendChild(wrap)}bindQuickButtons(wrap)}
  function bindQuickButtons(wrap){var buttons=wrap.querySelectorAll('[data-quick]');for(var b=0;b<buttons.length;b++){buttons[b].onclick=function(){var index=Number(this.getAttribute('data-quick')),meal=meals[index],btn=this;if(!meal||btn.disabled){return}btn.className='quickMealBtn saving';btn.disabled=true;haptic('light');request('choose_meal',{slot:meal.slot,option_index:90,variant_key:meal.variant}).then(function(data){btn.className='quickMealBtn done';btn.innerHTML='<div class="quickMealTop"><span class="quickMealIcon">✓</span><span class="quickMealKcal">Guardado</span></div><div><div class="quickMealName">'+meal.name+'</div><div class="quickMealDesc">Actualizado al instante</div></div>';if(data&&data.diet){patchDietView(data.diet)}haptic('medium')}).catch(function(error){btn.className='quickMealBtn';btn.disabled=false;alertMessage(error&&error.message?error.message:String(error))})}}}
  function refreshDietQuietly(){request('diet',{}).then(function(d){patchDietView(d);ensureQuickMeals()}).catch(function(){})}
  function observe(){ensureQuickMeals();var target=document.getElementById('diet');if(target&&window.MutationObserver){var observer=new MutationObserver(function(){ensureQuickMeals()});observer.observe(target,{childList:true,subtree:false})}else{window.setInterval(ensureQuickMeals,700)}var nav=document.querySelectorAll('.nav button');for(var i=0;i<nav.length;i++){if(nav[i].getAttribute('data-tab')==='diet'){nav[i].addEventListener('click',function(){setTimeout(refreshDietQuietly,80)})}}}
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',observe)}else{observe()}
})();

(function(){
  function loadWorkout(){
    if(!document.querySelector('link[data-fv-workout]')){var l=document.createElement('link');l.rel='stylesheet';l.href='/workout-v1.css?v=2993e67';l.setAttribute('data-fv-workout','1');document.head.appendChild(l)}
    if(!document.querySelector('script[data-fv-workout]')){var s=document.createElement('script');s.src='/workout-v2.js?v=cfe81f1';s.setAttribute('data-fv-workout','1');document.body.appendChild(s)}
  }
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',loadWorkout)}else{loadWorkout()}
})();
