(function(){
  function tg(){try{return window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null}catch(e){return null}}
  function isFullscreen(){var x=tg();try{return !!(x&&x.isFullscreen)}catch(e){return false}}
  function topInset(){var x=tg(),safe=0,content=0;try{if(x&&x.safeAreaInset){safe=Number(x.safeAreaInset.top||0)}}catch(e){}try{if(x&&x.contentSafeAreaInset){content=Number(x.contentSafeAreaInset.top||0)}}catch(e){}return Math.max(0,safe,content)}
  function ensureStyle(){if(document.getElementById('fvSafeAreaV2Style')){return}var s=document.createElement('style');s.id='fvSafeAreaV2Style';s.textContent=':root{--fv-tg-safe-top:0px}html.fvFullscreenSafe .app{padding-top:calc(var(--fv-tg-safe-top) + env(safe-area-inset-top,0px) + 8px)!important}html.fvFullscreenSafe .topbar{position:static!important;top:auto!important;background:linear-gradient(var(--bg) 76%,rgba(9,11,15,0))!important;border-bottom:0!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}@media(max-width:390px){html.fvFullscreenSafe .app{padding-top:calc(var(--fv-tg-safe-top) + env(safe-area-inset-top,0px) + 7px)!important}}';document.head.appendChild(s)}
  function loadAdvanced(){if(!document.querySelector('link[data-fv-advanced]')){var l=document.createElement('link');l.rel='stylesheet';l.href='/advanced-v1.css?v=3dbff39';l.setAttribute('data-fv-advanced','1');document.head.appendChild(l)}if(!document.querySelector('script[data-fv-advanced]')){var s=document.createElement('script');s.src='/advanced-v1.js?v=b2fc32e';s.setAttribute('data-fv-advanced','1');document.body.appendChild(s)}}
  function apply(){var root=document.documentElement,top=topInset(),on=isFullscreen();ensureStyle();try{root.style.setProperty('--fv-tg-safe-top',top+'px')}catch(e){}if(root.classList){if(on){root.classList.add('fvFullscreenSafe')}else{root.classList.remove('fvFullscreenSafe')}}}
  function refresh(){apply();setTimeout(apply,80);setTimeout(apply,260);setTimeout(apply,700)}
  function install(){ensureStyle();loadAdvanced();var x=tg();try{if(x&&typeof x.onEvent==='function'){x.onEvent('fullscreenChanged',refresh);x.onEvent('safeAreaChanged',refresh);x.onEvent('contentSafeAreaChanged',refresh);x.onEvent('viewportChanged',refresh)}}catch(e){}refresh()}
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',install)}else{install()}
})();
