(function(){
  var workoutClosed=false;
  function tg(){try{return window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null}catch(e){return null}}
  function initData(){var x=tg();try{return x&&x.initData?x.initData:''}catch(e){return ''}}
  function haptic(){var x=tg();try{if(x&&x.HapticFeedback){x.HapticFeedback.impactOccurred('light')}}catch(e){}}
  function state(){var x=tg();try{return !!(x&&x.isFullscreen)}catch(e){return false}}
  function topInset(){var x=tg(),a=0,b=0;try{if(x&&x.safeAreaInset){a=Number(x.safeAreaInset.top||0)}}catch(e){}try{if(x&&x.contentSafeAreaInset){b=Number(x.contentSafeAreaInset.top||0)}}catch(e){}return Math.max(0,a,b)}
  function lockVerticalSwipes(){var x=tg();try{if(x&&typeof x.disableVerticalSwipes==='function'){x.disableVerticalSwipes()}}catch(e){}}
  function installSafeCss(){if(document.getElementById('fvFullscreenSafeCss')){return}var s=document.createElement('style');s.id='fvFullscreenSafeCss';s.textContent=':root{--fv-tg-safe-top:0px}html,body{overscroll-behavior-y:none}html.fvFullscreenOn .app{padding-top:calc(var(--fv-tg-safe-top) + env(safe-area-inset-top,0px) + 8px)!important}html.fvFullscreenOn .topbar{position:relative!important;top:auto!important;margin:0!important;padding:8px 0 12px!important;background:transparent!important;border-bottom:0!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}html.fvFullscreenOn .topbar:after{content:"";position:absolute;left:0;right:0;bottom:0;height:1px;background:rgba(255,255,255,.04)}html.fvKeyboardOpen .nav{opacity:0!important;visibility:hidden!important;pointer-events:none!important;transform:translateY(120%)!important}html.fvKeyboardOpen body{padding-bottom:0!important}@media(max-width:390px){html.fvFullscreenOn .app{padding-top:calc(var(--fv-tg-safe-top) + env(safe-area-inset-top,0px) + 7px)!important}}';document.head.appendChild(s)}
  function isTyping(el){if(!el){return false}var tag=String(el.tagName||'').toLowerCase();return tag==='input'||tag==='textarea'||el.isContentEditable===true}
  function syncKeyboardClass(){var root=document.documentElement;if(!root||!root.classList){return}if(isTyping(document.activeElement)){root.classList.add('fvKeyboardOpen')}else{root.classList.remove('fvKeyboardOpen')}}
  function installKeyboardGuard(){document.addEventListener('focusin',function(e){if(isTyping(e.target)){var root=document.documentElement;if(root&&root.classList){root.classList.add('fvKeyboardOpen')}}},true);document.addEventListener('focusout',function(){setTimeout(syncKeyboardClass,120)},true)}
  function requestDaySummary(){return fetch(window.location.href,{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':initData()},body:JSON.stringify({action:'day_summary',payload:{}})}).then(function(r){return r.text().then(function(t){var j;try{j=JSON.parse(t)}catch(e){return null}if(!r.ok||!j||!j.ok){return null}return j.data||null})})}
  function applyWorkoutClosed(){var root=document.getElementById('work');if(!root){return}if(root.classList){root.classList.remove('fvFocusMode')}var controls=document.getElementById('fvWorkoutControls');if(controls){controls.style.display='none'}var banners=root.querySelectorAll('.activebanner');for(var i=0;i<banners.length;i++){if(banners[i].parentNode){banners[i].parentNode.removeChild(banners[i])}}var hero=root.querySelector('.hero');if(hero){var pill=hero.querySelector('.pill');if(pill){pill.className='pill';pill.textContent='Lectura'}}}
  function reconcileWorkoutClosed(){if(!document.getElementById('work')){return}requestDaySummary().then(function(d){workoutClosed=!!(d&&d.session&&String(d.session.workout_status||'').toLowerCase()==='closed');if(workoutClosed){applyWorkoutClosed()}}).catch(function(){})}
  function scheduleWorkoutReconcile(){setTimeout(reconcileWorkoutClosed,80);setTimeout(reconcileWorkoutClosed,320);setTimeout(reconcileWorkoutClosed,900)}
  function findButton(t){while(t&&t!==document){if(String(t.tagName||'').toLowerCase()==='button'){return t}t=t.parentNode}return null}
  function installWorkoutReconcile(){document.addEventListener('click',function(e){var b=findButton(e.target);if(!b){return}if(b.id==='fvStart'&&workoutClosed){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation){e.stopImmediatePropagation()}applyWorkoutClosed();return}if(b.id==='fvFinish'||b.id==='refresh'||(b.getAttribute&&b.getAttribute('data-tab')==='work')||(b.getAttribute&&b.getAttribute('data-day'))){scheduleWorkoutReconcile()}},true);reconcileWorkoutClosed();setTimeout(reconcileWorkoutClosed,450);setTimeout(reconcileWorkoutClosed,1200)}
  function applySafeArea(){var root=document.documentElement,on=state(),top=topInset();installSafeCss();lockVerticalSwipes();try{root.style.setProperty('--fv-tg-safe-top',top+'px')}catch(e){}if(root.classList){if(on){root.classList.add('fvFullscreenOn')}else{root.classList.remove('fvFullscreenOn')}}}
  function sync(){var b=document.getElementById('fvFullscreenBtn');applySafeArea();syncKeyboardClass();if(!b){return}var on=state();b.className='iconbtn'+(on?' on':'');b.textContent='⛶';b.setAttribute('aria-label',on?'Salir de pantalla completa':'Pantalla completa');b.title=on?'Salir de pantalla completa':'Pantalla completa'}
  function deferredSync(){sync();setTimeout(sync,80);setTimeout(sync,260);setTimeout(sync,700)}
  function toggle(){var x=tg();if(!x){return}haptic();lockVerticalSwipes();try{
    if(state()&&typeof x.exitFullscreen==='function'){x.exitFullscreen();deferredSync();return}
    if(typeof x.requestFullscreen==='function'){x.requestFullscreen();deferredSync();return}
    if(typeof x.expand==='function'){x.expand();var b=document.getElementById('fvFullscreenBtn');if(b){b.className='iconbtn unsupported';b.title='Vista ampliada';b.setAttribute('aria-label','Vista ampliada')}return}
  }catch(e){try{if(typeof x.expand==='function'){x.expand()}}catch(ignore){}}
  }
  function install(){installSafeCss();installKeyboardGuard();installWorkoutReconcile();lockVerticalSwipes();var actions=document.querySelector('.topactions'),beta=actions?actions.querySelector('.beta'):null;if(!actions||!beta||document.getElementById('fvFullscreenBtn')){deferredSync();return}var b=document.createElement('button');b.id='fvFullscreenBtn';b.className='iconbtn';b.type='button';b.textContent='⛶';b.setAttribute('aria-label','Pantalla completa');b.title='Pantalla completa';b.onclick=toggle;actions.insertBefore(b,beta);var x=tg();try{if(x&&typeof x.onEvent==='function'){x.onEvent('fullscreenChanged',deferredSync);x.onEvent('fullscreenFailed',deferredSync);x.onEvent('safeAreaChanged',deferredSync);x.onEvent('contentSafeAreaChanged',deferredSync);x.onEvent('viewportChanged',deferredSync)}}catch(e){}deferredSync()}
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',install)}else{install()}
})();
