(function(){
  var loading=false,refreshTimer=null,restTimer=null,restUntil=0;
  function tg(){try{return window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null}catch(e){return null}}
  function initData(){var x=tg();try{return x&&x.initData?x.initData:''}catch(e){return ''}}
  function haptic(type){var x=tg();try{if(x&&x.HapticFeedback){x.HapticFeedback.impactOccurred(type||'light')}}catch(e){}}
  function alertMsg(text){var x=tg();try{if(x&&x.showAlert){x.showAlert(text);return}}catch(e){}window.alert(text)}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function fmt(v){var n=Number(v||0);if(!isFinite(n)){return '0'}return String(Math.round(n*100)/100).replace('.',',')}
  function request(action,payload){return fetch(window.location.href,{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':initData()},body:JSON.stringify({action:action,payload:payload||{}})}).then(function(r){return r.text().then(function(t){var j;try{j=JSON.parse(t)}catch(e){throw new Error('Respuesta no válida')}if(!r.ok||!j.ok){throw new Error(j.reason||j.error||('HTTP '+r.status))}return j.data})})}
  function friendly(e){var m=e&&e.message?e.message:String(e);var map={workout_already_active:'Ya hay otro entrenamiento activo.',workout_boundary:'No hay más ejercicios en esa dirección.',invalid_set_input:'Formato no válido. Prueba 22,5x4 o 22,5: 15,14,12,10.',no_sets:'Todavía no hay series para modificar.',no_active_workout:'No hay entrenamiento activo.',exercise_not_found:'Ejercicio no disponible.',day_closed:'El día está cerrado.',full_free_day:'El día está marcado como libre completo.'};return map[m]||m}
  function selectedDay(){var b=document.querySelector('#work .daychip.on');var m=b?String(b.textContent||'').match(/(\d+)/):null;return m?Number(m[1]):1}
  function openSheet(html){var o=document.getElementById('overlay'),s=document.getElementById('sheet');if(!o||!s){return} s.innerHTML=html;o.className='overlay on';var c=document.getElementById('fvSheetClose');if(c){c.onclick=function(){o.className='overlay'}}}
  function setText(s){var w=Number(s.weight_kg||0),x='';if(w>0){x+=fmt(w)+' kg × '}x+=(s.reps==null?'?':String(s.reps));if(s.to_failure){x+=' 🔥'}if(s.assisted){x+=' 🤝'}return x}
  function currentSetsHtml(a){var sets=a&&a.currentSets?a.currentSets:[],html='';if(!sets.length){return '<div class="fvEmptySets">Aún no hay series en este ejercicio.</div>'}for(var i=0;i<sets.length;i++){html+='<div class="fvSetRow"><span class="fvSetNum">'+(i+1)+'</span><strong>'+esc(setText(sets[i]))+'</strong></div>'}return html}
  function prevHtml(a){if(!a||!a.previous||!a.previous.sets||!a.previous.sets.length){return 'Sin referencia anterior'}var p=a.previous,parts=[];for(var i=0;i<p.sets.length;i++){parts.push(setText(p.sets[i]))}return esc(p.date)+' · '+esc(parts.join(' · '))}
  function activeHtml(a){var e=a.exercise||{},ins=a.insight||{},suggest=ins.suggested_weight!=null?fmt(ins.suggested_weight)+' kg':'—';return '<div class="fvActiveCard">'+
    '<div class="fvActiveTop"><div><div class="fvEy">▶️ EJERCICIO ACTIVO</div><div class="fvActiveTitle"><span>'+esc(e.exercise_code||'')+'</span> '+esc(e.exercise_name||'')+'</div><div class="fvPrescription">'+esc(e.prescription||'')+'</div></div><div class="fvSuggest"><small>Sugerido</small><b>'+esc(suggest)+'</b></div></div>'+
    '<div class="fvReference"><span>Última</span><div>'+prevHtml(a)+'</div></div>'+
    '<div class="fvCurrent"><div class="fvSubhead">Series de hoy</div>'+currentSetsHtml(a)+'</div>'+
    '<div class="fvEntry"><input id="fvSetInput" class="fvSetInput" inputmode="decimal" placeholder="22,5x4"><button id="fvAddSet" class="fvPrimary">Registrar</button></div>'+
    '<div class="fvHint">También: 22,5: 15,14,12,10 · 20 / 22,5 / 25 · 15,14,12,10</div>'+
    '<div class="fvNav"><button id="fvPrev">◀ Anterior</button><button id="fvNext">Siguiente ▶</button></div>'+
    '<div class="fvFlags"><button id="fvFailure">🔥 Fallo</button><button id="fvAssist">🤝 Asistida</button><button id="fvUndo">↩ Serie</button></div>'+
    '<div class="fvTimerWrap"><div class="fvSubhead">Descanso <span id="fvTimer">Listo</span></div><div class="fvTimers"><button data-rest="60">60 s</button><button data-rest="90">90 s</button><button data-rest="120">120 s</button></div></div>'+
    '<div class="fvTools"><button id="fvHistory">📚 Historial</button><button id="fvPrs">🏆 PRs</button></div>'+
    '<button id="fvFinish" class="fvFinish">🏁 Terminar entrenamiento</button></div>'}
  function inactiveHtml(day){return '<div class="fvStartCard"><div><div class="fvEy">MODO BESTIA</div><div class="fvStartTitle">Día '+day+'</div><div class="fvStartMeta">Inicia una sesión real y activa el ejercicio 1.</div></div><button id="fvStart" class="fvPrimary">▶ Empezar Día '+day+'</button></div>'}
  function place(html){var root=document.getElementById('work');if(!root){return}var old=document.getElementById('fvWorkoutControls');if(old){old.parentNode.removeChild(old)}var box=document.createElement('div');box.id='fvWorkoutControls';box.innerHTML=html;var chips=root.querySelector('.daychips');if(chips&&chips.nextSibling){chips.parentNode.insertBefore(box,chips.nextSibling)}else if(chips){chips.parentNode.appendChild(box)}else{root.insertBefore(box,root.firstChild)}return box}
  function refreshBase(){var r=document.getElementById('refresh');if(r){r.click()}if(refreshTimer){clearTimeout(refreshTimer)}refreshTimer=setTimeout(function(){ensure(true)},650)}
  function doAction(action,payload,after){loading=true;haptic('light');request(action,payload).then(function(data){loading=false;haptic('medium');if(after){after(data)}else{refreshBase()}}).catch(function(e){loading=false;alertMsg(friendly(e))})}
  function startRest(sec){if(restTimer){clearInterval(restTimer)}restUntil=Date.now()+sec*1000;function tick(){var el=document.getElementById('fvTimer');var left=Math.max(0,Math.ceil((restUntil-Date.now())/1000));if(el){el.textContent=left>0?left+' s':'¡YA!'}if(left<=0){clearInterval(restTimer);restTimer=null;haptic('heavy');var x=tg();try{if(x&&x.HapticFeedback){x.HapticFeedback.notificationOccurred('success')}}catch(e){}}}tick();restTimer=setInterval(tick,500)}
  function bind(a){var start=document.getElementById('fvStart');if(start){start.onclick=function(){doAction('start_workout',{day:selectedDay()})};return}var add=document.getElementById('fvAddSet'),inp=document.getElementById('fvSetInput');if(add){add.onclick=function(){var v=inp?String(inp.value||'').trim():'';if(!v){alertMsg('Escribe una serie, por ejemplo 22,5x4.');return}doAction('add_sets',{text:v})}}if(inp){inp.onkeydown=function(e){if(e.key==='Enter'&&add){add.click()}}}var prev=document.getElementById('fvPrev'),next=document.getElementById('fvNext');if(prev){prev.onclick=function(){doAction('navigate_workout',{direction:-1})}}if(next){next.onclick=function(){doAction('navigate_workout',{direction:1})}}var fail=document.getElementById('fvFailure'),assist=document.getElementById('fvAssist'),undo=document.getElementById('fvUndo');if(fail){fail.onclick=function(){doAction('flag_last_set',{kind:'to_failure'})}}if(assist){assist.onclick=function(){doAction('flag_last_set',{kind:'assisted'})}}if(undo){undo.onclick=function(){doAction('undo_last_set',{})}}var timers=document.querySelectorAll('#fvWorkoutControls [data-rest]');for(var i=0;i<timers.length;i++){timers[i].onclick=function(){startRest(Number(this.getAttribute('data-rest')))}}var hist=document.getElementById('fvHistory');if(hist){hist.onclick=function(){doAction('exercise_history',{},function(d){var html='<div class="fvSheetHead"><div><div class="fvEy">📚 HISTORIAL</div><div class="fvSheetTitle">'+esc(d.exercise?d.exercise.exercise_name:'')+'</div></div><button id="fvSheetClose" class="iconbtn">×</button></div>';var h=d.history||[];if(!h.length){html+='<div class="empty">Sin sesiones anteriores.</div>'}for(var z=0;z<h.length;z++){var parts=[];for(var q=0;q<h[z].sets.length;q++){parts.push(setText(h[z].sets[q]))}html+='<div class="fvHistoryRow"><b>'+esc(h[z].date)+'</b><div>'+esc(parts.join(' · '))+'</div></div>'}openSheet(html)})}}var prs=document.getElementById('fvPrs');if(prs){prs.onclick=function(){doAction('exercise_prs',{},function(d){var p=d.prs,html='<div class="fvSheetHead"><div><div class="fvEy">🏆 PRs</div><div class="fvSheetTitle">'+esc(d.exercise?d.exercise.exercise_name:'')+'</div></div><button id="fvSheetClose" class="iconbtn">×</button></div>';if(!p){html+='<div class="empty">Aún sin registros.</div>'}else{html+='<div class="fvPrGrid"><div><small>Peso máx.</small><b>'+fmt(p.maxWeight)+' kg</b></div><div><small>Máx. reps</small><b>'+p.maxReps+'</b></div><div><small>e1RM</small><b>'+fmt(p.e1rm)+' kg</b></div><div><small>Volumen/serie</small><b>'+Math.round(Number(p.maxVolume||0))+'</b></div></div>'}openSheet(html)})}}var finish=document.getElementById('fvFinish');if(finish){finish.onclick=function(){if(window.confirm('¿Terminar el entrenamiento?')){doAction('finish_workout',{})}}}
    var cards=document.querySelectorAll('#work .exerciseCard');if(a&&a.workout&&Number(a.workout.workout_day)===selectedDay()){for(var c=0;c<cards.length;c++){var code=cards[c].querySelector('.excode');if(!code){continue}var v=String(code.textContent||'').trim();cards[c].setAttribute('data-fv-code',v);if(a.exercise&&v===String(a.exercise.exercise_code)){cards[c].className+=' fvExerciseActive'}cards[c].onclick=function(){var code2=this.getAttribute('data-fv-code');if(code2){doAction('activate_exercise',{code:code2})}}}}
  }
  function render(data){var a=data&&data.active?data.active:null,day=selectedDay();var box=place(a?activeHtml(a):inactiveHtml(day));if(box){bind(a)}}
  function ensure(force){var root=document.getElementById('work');if(!root||loading){return}if(!force&&document.getElementById('fvWorkoutControls')){return}loading=true;request('workouts',{}).then(function(d){loading=false;render(d)}).catch(function(e){loading=false})}
  function observe(){ensure(false);var root=document.getElementById('work');if(root&&window.MutationObserver){var o=new MutationObserver(function(){setTimeout(function(){ensure(false)},40)});o.observe(root,{childList:true,subtree:false})}var nav=document.querySelectorAll('.nav button');for(var i=0;i<nav.length;i++){if(nav[i].getAttribute('data-tab')==='work'){nav[i].addEventListener('click',function(){setTimeout(function(){ensure(true)},250)})}}}
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',observe)}else{observe()}
})();
