(function(){
  var loading=false,restTimer=null,restUntil=0,audioCtx=null;
  function tg(){try{return window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null}catch(e){return null}}
  function initData(){var x=tg();try{return x&&x.initData?x.initData:''}catch(e){return ''}}
  function haptic(type){var x=tg();try{if(x&&x.HapticFeedback){x.HapticFeedback.impactOccurred(type||'light')}}catch(e){}}
  function alertMsg(text){var x=tg();try{if(x&&x.showAlert){x.showAlert(text);return}}catch(e){}window.alert(text)}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function fmt(v){var n=Number(v||0);if(!isFinite(n)){return '0'}return String(Math.round(n*100)/100).replace('.',',')}
  function request(action,payload){return fetch(window.location.href,{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':initData()},body:JSON.stringify({action:action,payload:payload||{}})}).then(function(r){return r.text().then(function(t){var j;try{j=JSON.parse(t)}catch(e){throw new Error('Respuesta no válida')}if(!r.ok||!j.ok){throw new Error(j.reason||j.error||('HTTP '+r.status))}return j.data})})}
  function friendly(e){var m=e&&e.message?e.message:String(e);var map={workout_already_active:'Ya hay otro entrenamiento activo.',workout_boundary:'No hay más ejercicios en esa dirección.',invalid_set_input:'Formato no válido. Prueba 22,5x4 o 22,5: 15,14,12,10.',no_sets:'Todavía no hay series para modificar.',no_active_workout:'No hay entrenamiento activo.',exercise_not_found:'Ejercicio no disponible.',day_closed:'El día está cerrado.',full_free_day:'El día está marcado como libre completo.'};return map[m]||m}
  function selectedDay(){var b=document.querySelector('#work .daychip.on');var m=b?String(b.textContent||'').match(/(\d+)/):null;return m?Number(m[1]):1}
  function openSheet(html){var o=document.getElementById('overlay'),s=document.getElementById('sheet');if(!o||!s){return}s.innerHTML=html;o.className='overlay on';var c=document.getElementById('fvSheetClose');if(c){c.onclick=function(){o.className='overlay'}}}
  function closeSheet(){var o=document.getElementById('overlay');if(o){o.className='overlay'}}
  function setText(s){var w=Number(s.weight_kg||0),x='';if(w>0){x+=fmt(w)+'×'}x+=(s.reps==null?'?':String(s.reps));if(s.to_failure){x+=' 🔥'}if(s.assisted){x+=' 🤝'}return x}
  function currentSetsHtml(a){var sets=a&&a.currentSets?a.currentSets:[],html='';if(!sets.length){return '<div class="fvEmptySets">Primera serie pendiente.</div>'}html='<div class="fvSetsStrip">';for(var i=0;i<sets.length;i++){html+='<span class="fvSetChip"><i>'+(i+1)+'</i>'+esc(setText(sets[i]))+'</span>'}return html+'</div>'}
  function prevHtml(a){if(!a||!a.previous||!a.previous.sets||!a.previous.sets.length){return 'Sin referencia anterior'}var p=a.previous,parts=[];for(var i=0;i<p.sets.length;i++){parts.push(setText(p.sets[i]))}return esc(parts.join(' · '))}
  function suggested(a){var i=a&&a.insight?a.insight:{};return i.suggested_weight!=null?fmt(i.suggested_weight)+' kg':'—'}
  function progressLabel(a){var p=a&&a.plan?a.plan:[],code=a&&a.exercise?String(a.exercise.exercise_code||''):'';var idx=-1;for(var i=0;i<p.length;i++){if(String(p[i].exercise_code)===code){idx=i;break}}return idx>=0?'Ejercicio '+(idx+1)+' de '+p.length:'Entrenamiento'}
  function targetSeries(a){var p=String(a&&a.exercise&&a.exercise.prescription?a.exercise.prescription:''),re=/(\d+)\s*[x×]/gi,m,total=0;while((m=re.exec(p))!==null){total+=Number(m[1]||0)}return total>0?total:null}
  function hasNextExercise(a){var p=a&&a.plan?a.plan:[],code=a&&a.exercise?String(a.exercise.exercise_code||''):'';for(var i=0;i<p.length;i++){if(String(p[i].exercise_code)===code){return i<p.length-1}}return false}
  function focusEntry(){var n=document.getElementById('fvSetInput');if(n){n.focus()}}
  function activeHtml(a){var e=a.exercise||{},hasSets=a.currentSets&&a.currentSets.length;return '<div class="fvFocusCard">'+
    '<div class="fvFocusHeader"><div><div class="fvFocusDay">🐗 Día '+esc(a.workout.workout_day)+' · '+esc(progressLabel(a))+'</div><div class="fvFocusTitle"><span class="fvFocusCode">'+esc(e.exercise_code||'')+'</span>'+esc(e.exercise_name||'')+'</div><div class="fvPrescription">'+esc(e.prescription||'')+'</div></div><button id="fvMore" class="fvMore" aria-label="Más opciones">•••</button></div>'+
    '<div class="fvReference"><div class="fvReferenceTop"><span class="fvReferenceLabel">Última referencia</span><span class="fvSuggested">Sugerido: '+esc(suggested(a))+'</span></div><div class="fvReferenceText">'+prevHtml(a)+'</div></div>'+
    '<div class="fvCurrent"><div class="fvSubhead">Series de hoy</div>'+currentSetsHtml(a)+'</div>'+
    '<div class="fvEntry"><input id="fvSetInput" class="fvSetInput" type="text" inputmode="text" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="22,5x4"><button id="fvAddSet" class="fvPrimary">Registrar</button></div>'+
    '<div class="fvHint">También: 22,5: 15,14,12,10 · 20 / 22,5 / 25 · 15,14,12,10</div>'+
    '<div class="fvNav"><button id="fvPrev">◀ Anterior</button><button id="fvNext">Siguiente ▶</button></div>'+
    (hasSets?'<div class="fvLastTools"><button id="fvFailure">🔥 Fallo</button><button id="fvAssist">🤝 Asistida</button><button id="fvUndo">↩ Deshacer</button></div>':'')+
    '<div class="fvRest"><div class="fvRestTop"><div><div class="fvReferenceLabel">Descanso</div><div id="fvTimer" class="fvTimerDisplay">Listo</div></div><div class="fvReferenceLabel">Aviso 3 s</div></div><div class="fvTimers"><button data-rest="60">60 s</button><button data-rest="90">90 s</button><button data-rest="120">120 s</button></div></div>'+
    '</div>'}
  function inactiveHtml(day){return '<div class="fvStartCard"><div><div class="fvEy">MODO BESTIA</div><div class="fvStartTitle">Día '+day+'</div><div class="fvStartMeta">Elige el día y entra en modo foco.</div></div><button id="fvStart" class="fvPrimary">▶ Empezar Día '+day+'</button></div>'}
  function place(html,a){var root=document.getElementById('work');if(!root){return}if(a){root.classList.add('fvFocusMode')}else{root.classList.remove('fvFocusMode')}var old=document.getElementById('fvWorkoutControls');if(old){old.parentNode.removeChild(old)}var box=document.createElement('div');box.id='fvWorkoutControls';box.innerHTML=html;var chips=root.querySelector('.daychips');if(chips&&chips.nextSibling){chips.parentNode.insertBefore(box,chips.nextSibling)}else if(chips){chips.parentNode.appendChild(box)}else{root.insertBefore(box,root.firstChild)}return box}
  function armAudio(){try{var C=window.AudioContext||window.webkitAudioContext;if(!C){return}if(!audioCtx){audioCtx=new C()}if(audioCtx.state==='suspended'){audioCtx.resume()}}catch(e){}}
  function tone(freq,duration,delay){setTimeout(function(){try{if(!audioCtx){return}var o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(0.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(0.12,audioCtx.currentTime+0.01);g.gain.exponentialRampToValueAtTime(0.0001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration+0.02)}catch(e){}},delay)}
  function finishAlert(){var x=tg(),started=Date.now();try{if(window.navigator&&navigator.vibrate){navigator.vibrate(3000)}}catch(e){}try{if(x&&x.HapticFeedback){x.HapticFeedback.notificationOccurred('success')}}catch(e){}function pulse(){try{if(x&&x.HapticFeedback){x.HapticFeedback.impactOccurred('heavy')}}catch(e){}if(Date.now()-started<2750){setTimeout(pulse,250)}}pulse();tone(880,.14,0);tone(1050,.14,650);tone(880,.14,1300);tone(1050,.14,1950);tone(1180,.18,2600)}
  function timerText(left){var m=Math.floor(left/60),s=left%60;return m>0?m+':'+(s<10?'0':'')+s:left+' s'}
  function tickTimer(){var el=document.getElementById('fvTimer'),left=Math.max(0,Math.ceil((restUntil-Date.now())/1000));if(!restUntil){if(el){el.textContent='Listo';el.className='fvTimerDisplay'}return}if(el){el.textContent=left>0?timerText(left):'¡YA!';el.className='fvTimerDisplay'+(left>0?' running':'')}if(left<=0){if(restTimer){clearInterval(restTimer);restTimer=null}restUntil=0;finishAlert()}}
  function startRest(sec){armAudio();if(restTimer){clearInterval(restTimer)}restUntil=Date.now()+sec*1000;tickTimer();restTimer=setInterval(tickTimer,250);haptic('light');var buttons=document.querySelectorAll('#fvWorkoutControls [data-rest]');for(var i=0;i<buttons.length;i++){buttons[i].className=Number(buttons[i].getAttribute('data-rest'))===sec?'on':''}}
  function updateActive(data){if(data&&Object.prototype.hasOwnProperty.call(data,'active')){render({active:data.active});return true}return false}
  function doAction(action,payload,after){if(loading){return}loading=true;haptic('light');request(action,payload).then(function(data){loading=false;if(after){after(data);return}if(updateActive(data)){haptic('medium');return}ensure(true)}).catch(function(e){loading=false;alertMsg(friendly(e))})}
  function afterAdd(data){var a=data&&data.active?data.active:null;if(!a){ensure(true);return}var target=targetSeries(a),count=a.currentSets?a.currentSets.length:0;if(target&&count>=target&&hasNextExercise(a)){request('navigate_workout',{direction:1}).then(function(n){if(n&&n.active){render({active:n.active});haptic('medium');focusEntry()}else{ensure(true)}}).catch(function(e){render({active:a});alertMsg(friendly(e))});return}render({active:a});haptic('medium');focusEntry()}
  function showHistory(){doAction('exercise_history',{},function(d){var html='<div class="fvSheetHead"><div><div class="fvEy">📚 HISTORIAL</div><div class="fvSheetTitle">'+esc(d.exercise?d.exercise.exercise_name:'')+'</div></div><button id="fvSheetClose" class="iconbtn">×</button></div>';var h=d.history||[];if(!h.length){html+='<div class="empty">Sin sesiones anteriores.</div>'}for(var z=0;z<h.length;z++){var parts=[];for(var q=0;q<h[z].sets.length;q++){parts.push(setText(h[z].sets[q]))}html+='<div class="fvHistoryRow"><b>'+esc(h[z].date)+'</b><div>'+esc(parts.join(' · '))+'</div></div>'}openSheet(html)})}
  function showPrs(){doAction('exercise_prs',{},function(d){var p=d.prs,html='<div class="fvSheetHead"><div><div class="fvEy">🏆 PRs</div><div class="fvSheetTitle">'+esc(d.exercise?d.exercise.exercise_name:'')+'</div></div><button id="fvSheetClose" class="iconbtn">×</button></div>';if(!p){html+='<div class="empty">Aún sin registros.</div>'}else{html+='<div class="fvPrGrid"><div><small>Peso máx.</small><b>'+fmt(p.maxWeight)+' kg</b></div><div><small>Máx. reps</small><b>'+p.maxReps+'</b></div><div><small>e1RM</small><b>'+fmt(p.e1rm)+' kg</b></div><div><small>Volumen/serie</small><b>'+Math.round(Number(p.maxVolume||0))+'</b></div></div>'}openSheet(html)})}
  function patchFinishedBase(day){var root=document.getElementById('work');if(!root){return}var banner=root.querySelector('.activebanner');if(banner&&banner.parentNode){banner.parentNode.removeChild(banner)}var pill=root.querySelector('.hero .pill');if(pill){pill.className='pill';pill.textContent='Lectura'}var small=root.querySelector('.hero .small');if(small){small.textContent='Entrenamiento Día '+day+' finalizado'} }
  function showMore(a){var html='<div class="fvSheetHead"><div><div class="fvEy">DÍA '+esc(a.workout.workout_day)+'</div><div class="fvSheetTitle">Más opciones</div></div><button id="fvSheetClose" class="iconbtn">×</button></div><div class="fvMenuGrid"><button id="fvRoutine" class="fvMenuBtn">📋 Rutina</button><button id="fvHistory" class="fvMenuBtn">📚 Historial</button><button id="fvPrs" class="fvMenuBtn">🏆 PRs</button><button id="fvFinish" class="fvMenuBtn danger">🏁 Terminar</button></div>';openSheet(html);document.getElementById('fvHistory').onclick=showHistory;document.getElementById('fvPrs').onclick=showPrs;document.getElementById('fvFinish').onclick=function(){if(window.confirm('¿Terminar el entrenamiento?')){var day=Number(a.workout.workout_day);closeSheet();doAction('finish_workout',{},function(){render({active:null});patchFinishedBase(day);haptic('medium')})}};document.getElementById('fvRoutine').onclick=function(){showRoutine(a)}}
  function showRoutine(a){var p=a.plan||[],html='<div class="fvSheetHead"><div><div class="fvEy">📋 DÍA '+esc(a.workout.workout_day)+'</div><div class="fvSheetTitle">Rutina</div></div><button id="fvSheetClose" class="iconbtn">×</button></div><div class="fvRoutineList">';for(var i=0;i<p.length;i++){var on=a.exercise&&String(a.exercise.exercise_code)===String(p[i].exercise_code);html+='<button class="fvRoutineBtn'+(on?' active':'')+'" data-code="'+esc(p[i].exercise_code)+'"><b>'+esc(p[i].exercise_code)+'</b><span>'+esc(p[i].exercise_name)+' · '+esc(p[i].prescription)+'</span></button>'}html+='</div>';openSheet(html);var rows=document.querySelectorAll('.fvRoutineBtn[data-code]');for(var z=0;z<rows.length;z++){rows[z].onclick=function(){var code=this.getAttribute('data-code');closeSheet();doAction('activate_exercise',{code:code})}}}
  function bind(a){var start=document.getElementById('fvStart');if(start){start.onclick=function(){doAction('start_workout',{day:selectedDay()})};return}var add=document.getElementById('fvAddSet'),inp=document.getElementById('fvSetInput');if(add){add.onclick=function(){var v=inp?String(inp.value||'').trim():'';if(!v){alertMsg('Escribe una serie, por ejemplo 22,5x4.');return}add.disabled=true;request('add_sets',{text:v}).then(function(data){add.disabled=false;if(inp){inp.value=''}afterAdd(data)}).catch(function(e){add.disabled=false;alertMsg(friendly(e))})}}if(inp){inp.onkeydown=function(e){if(e.key==='Enter'&&add){e.preventDefault();add.click()}}}var prev=document.getElementById('fvPrev'),next=document.getElementById('fvNext');if(prev){prev.onclick=function(){doAction('navigate_workout',{direction:-1})}}if(next){next.onclick=function(){doAction('navigate_workout',{direction:1})}}var fail=document.getElementById('fvFailure'),assist=document.getElementById('fvAssist'),undo=document.getElementById('fvUndo');if(fail){fail.onclick=function(){doAction('flag_last_set',{kind:'to_failure'})}}if(assist){assist.onclick=function(){doAction('flag_last_set',{kind:'assisted'})}}if(undo){undo.onclick=function(){doAction('undo_last_set',{})}}var timers=document.querySelectorAll('#fvWorkoutControls [data-rest]');for(var i=0;i<timers.length;i++){timers[i].onclick=function(){startRest(Number(this.getAttribute('data-rest')))}}var more=document.getElementById('fvMore');if(more){more.onclick=function(){showMore(a)}}tickTimer()}
  function render(data){var a=data&&data.active?data.active:null,day=a&&a.workout?Number(a.workout.workout_day):selectedDay();var box=place(a?activeHtml(a):inactiveHtml(day),a);if(box){bind(a)}}
  function ensure(force){var root=document.getElementById('work');if(!root||loading){return}if(!force&&document.getElementById('fvWorkoutControls')){return}loading=true;request('workouts',{}).then(function(d){loading=false;render(d)}).catch(function(){loading=false})}
  function observe(){ensure(false);var root=document.getElementById('work');if(root&&window.MutationObserver){var o=new MutationObserver(function(){setTimeout(function(){ensure(false)},40)});o.observe(root,{childList:true,subtree:false})}var nav=document.querySelectorAll('.nav button');for(var i=0;i<nav.length;i++){if(nav[i].getAttribute('data-tab')==='work'){nav[i].addEventListener('click',function(){setTimeout(function(){ensure(true)},220)})}}}
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',observe)}else{observe()}
})();
