(function(){
  var API='https://hhlxdzehiapvolyptfth.supabase.co/functions/v1/fitvalen-zepp-vision';
  var state={today:null,activityFile:null,sleepFile:null,review:null,loading:false};
  function tg(){try{return window.Telegram&&window.Telegram.WebApp?window.Telegram.WebApp:null}catch(e){return null}}
  function initData(){var x=tg();try{return x&&x.initData?x.initData:''}catch(e){return ''}}
  function haptic(){var x=tg();try{if(x&&x.HapticFeedback){x.HapticFeedback.impactOccurred('light')}}catch(e){}}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function text(v){return v==null?'':String(v)}
  function numText(v,dash){if(v===null||v===undefined||v===''){return dash===false?'':'—'}return String(v).replace('.',',')}
  function notify(t){var e=document.getElementById('toast');if(!e){return}e.textContent=t;e.className='toast on';setTimeout(function(){e.className='toast'},1900)}
  function request(action,payload){return fetch(API,{method:'POST',headers:{'content-type':'application/json','x-telegram-init-data':initData()},body:JSON.stringify({action:action,payload:payload||{}})}).then(function(r){return r.text().then(function(t){var j;try{j=JSON.parse(t)}catch(ignore){throw new Error('Respuesta Zepp no válida')}if(!r.ok||!j.ok){throw new Error(j.error||j.reason||('HTTP '+r.status))}return j.data})})}
  function closeSheet(){var o=document.getElementById('overlay');if(o){o.className='overlay'}}
  function openSheet(html){var o=document.getElementById('overlay'),s=document.getElementById('sheet');if(!o||!s){return}s.innerHTML=html;o.className='overlay on';var c=document.getElementById('fvZeppClose');if(c){c.onclick=closeSheet}}
  function sheetHead(title,sub){return '<div class="row"><div><div class="ey">ZEPP · '+esc(sub||'HOY')+'</div><div class="stat" style="margin-top:5px">'+esc(title)+'</div></div><button class="iconbtn" id="fvZeppClose">×</button></div>'}
  function duration(v){if(v===null||v===undefined){return '—'}var m=Number(v);if(!isFinite(m)){return '—'}var h=Math.floor(m/60),r=Math.round(m%60);return h>0?h+' h '+r+' min':r+' min'}
  function activityPresent(a){return !!a&&(a.steps!==null||a.distance_km!==null||a.activity_kcal!==null||a.total_kcal!==null||a.resting_kcal!==null||a.pai_total!==null||a.pai_today!==null)}
  function sleepPresent(s){return !!s&&(s.duration_min!==null||s.regularity_pct!==null||s.deep_min!==null||s.deep_pct!==null||s.rem_min!==null||s.rem_pct!==null||s.awake_min!==null||s.awake_count!==null)}
  function cache(d){state.today=d||{date:null,summary:null,sleep:null};renderCard();patchSummary()}
  function loadToday(){return request('zepp_get_today',{}).then(function(d){cache(d);return d}).catch(function(){renderCard();return null})}
  function renderCard(){var home=document.getElementById('home');if(!home||document.getElementById('fvZeppCard')){return}var anchor=document.getElementById('fvDayTools')||home.querySelector('.hero');if(!anchor||!anchor.parentNode){return}var box=document.createElement('div');box.id='fvZeppCard';var d=state.today||{},a=d.summary||null,s=d.sleep||null,has=!!(a||s);box.innerHTML='<div class="fvZeppHead"><div class="fvZeppTitle"><i class="fvZeppMark"></i><span>Zepp · Hoy</span></div><span class="fvZeppStatus '+(has?'on':'')+'">'+(has?'Datos preparados':'Sin importar')+'</span></div>'+
    '<div class="fvZeppMetrics">'+
      '<div class="fvZeppMetric"><b>'+(a&&a.steps!=null?esc(a.steps):'—')+'</b><span>Pasos</span></div>'+
      '<div class="fvZeppMetric"><b>'+(a&&a.activity_kcal!=null?esc(a.activity_kcal):'—')+'</b><span>kcal actividad</span></div>'+
      '<div class="fvZeppMetric"><b>'+(a&&a.pai_total!=null?esc(a.pai_total):'—')+'</b><span>PAI</span></div>'+
      '<div class="fvZeppMetric"><b>'+(s?esc(duration(s.duration_min)):'—')+'</b><span>Sueño</span></div>'+
    '</div><button class="fvZeppAction" id="fvZeppOpen">'+(has?'Actualizar capturas':'Importar capturas')+'</button>';
  if(anchor.nextSibling){anchor.parentNode.insertBefore(box,anchor.nextSibling)}else{anchor.parentNode.appendChild(box)}var b=document.getElementById('fvZeppOpen');if(b){b.onclick=uploadSheet}}
  function refreshCard(){var old=document.getElementById('fvZeppCard');if(old&&old.parentNode){old.parentNode.removeChild(old)}renderCard()}
  function fileName(file){var n=file&&file.name?String(file.name):'Captura';return n.length>28?n.slice(0,25)+'…':n}
  function pickerState(id,file){var p=document.getElementById(id),st=p?p.querySelector('.fvZeppPickState'):null;if(!p||!st){return}if(file){p.className='fvZeppPicker ready';st.textContent='Lista · '+fileName(file)}else{p.className='fvZeppPicker';st.textContent='Elegir captura'}}
  function uploadSheet(){state.activityFile=null;state.sleepFile=null;var html=sheetHead('Importar capturas','HOY')+'<div class="small" style="margin-top:8px">Sube únicamente las dos pantallas acordadas de Zepp.</div><div class="fvZeppUploadGrid">'+
    '<label class="fvZeppPicker" id="fvZeppActivityPick"><input id="fvZeppActivityFile" type="file" accept="image/*"><strong>Actividad</strong><small>Pasos · distancia · calorías · PAI</small><span class="fvZeppPickState">Elegir captura</span></label>'+
    '<label class="fvZeppPicker" id="fvZeppSleepPick"><input id="fvZeppSleepFile" type="file" accept="image/*"><strong>Sueño</strong><small>Duración · regularidad · profunda · REM · despierto</small><span class="fvZeppPickState">Elegir captura</span></label></div>'+
    '<div class="fvZeppPrivacy">Las capturas se usan solo para interpretar los valores. FitValen guarda los datos confirmados, no las imágenes.</div><button class="actionbtn primary wide" style="margin-top:14px" id="fvZeppAnalyze" disabled>Analizar capturas</button>';
    openSheet(html);var af=document.getElementById('fvZeppActivityFile'),sf=document.getElementById('fvZeppSleepFile'),btn=document.getElementById('fvZeppAnalyze');function ready(){if(btn){btn.disabled=!(state.activityFile&&state.sleepFile)}}if(af){af.onchange=function(){state.activityFile=this.files&&this.files[0]?this.files[0]:null;pickerState('fvZeppActivityPick',state.activityFile);ready()}}if(sf){sf.onchange=function(){state.sleepFile=this.files&&this.files[0]?this.files[0]:null;pickerState('fvZeppSleepPick',state.sleepFile);ready()}}if(btn){btn.onclick=analyzeFiles}}
  function fileToData(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onerror=function(){reject(new Error('No se pudo leer la captura'))};r.onload=function(){var raw=String(r.result||'');var im=new Image();im.onerror=function(){resolve(raw)};im.onload=function(){try{var max=1800,w=im.width,h=im.height,scale=Math.min(1,max/Math.max(w,h)),cw=Math.max(1,Math.round(w*scale)),ch=Math.max(1,Math.round(h*scale)),c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=cw;c.height=ch;if(!ctx){resolve(raw);return}ctx.drawImage(im,0,0,cw,ch);resolve(c.toDataURL('image/jpeg',0.91))}catch(e){resolve(raw)}};im.src=raw};r.readAsDataURL(file)})}
  function friendlyError(e){var m=e&&e.message?e.message:String(e);if(m==='vision_not_configured'){return 'La visión de Zepp no está configurada en el servidor.'}if(m==='invalid_images'){return 'Revisa las dos capturas.'}if(m.indexOf('vision_api_')===0){return 'No se pudieron interpretar las capturas. Inténtalo de nuevo.'}return m}
  function analyzeFiles(){if(state.loading||!state.activityFile||!state.sleepFile){return}state.loading=true;var b=document.getElementById('fvZeppAnalyze');if(b){b.disabled=true;b.textContent='Analizando…'}Promise.all([fileToData(state.activityFile),fileToData(state.sleepFile)]).then(function(imgs){return request('zepp_analyze',{activity_image:imgs[0],sleep_image:imgs[1]})}).then(function(d){state.loading=false;state.review=d;reviewSheet(d);haptic()}).catch(function(e){state.loading=false;if(b){b.disabled=false;b.textContent='Analizar capturas'}notify(friendlyError(e))})}
  function input(id,label,v,mode){return '<div class="fvField"><label>'+esc(label)+'</label><input class="fvText" id="'+id+'" type="text" '+(mode?'inputmode="'+mode+'"':'')+' value="'+esc(numText(v,false))+'" placeholder="—"></div>'}
  function reviewSheet(d){var a=d&&d.activity?d.activity:{},s=d&&d.sleep?d.sleep:{},notes=d&&d.notes?d.notes:[],html=sheetHead('Revisar datos','HOY')+'<div class="small" style="margin-top:8px">Comprueba los valores antes de guardar. Los guiones de Zepp se mantienen como “sin dato”.</div><div class="fvZeppReviewTitle">Actividad</div><div class="fvZeppReviewGrid">'+
    input('fvZSteps','Pasos',a.steps,'numeric')+input('fvZDistance','Distancia km',a.distance_km,'decimal')+input('fvZActivityKcal','kcal actividad',a.activity_kcal,'numeric')+input('fvZRestingKcal','kcal reposo',a.resting_kcal,'numeric')+input('fvZTotalKcal','kcal total',a.total_kcal,'numeric')+input('fvZPaiTotal','PAI total',a.pai_total,'numeric')+input('fvZPaiToday','PAI hoy',a.pai_today,'numeric')+'</div><div class="fvZeppReviewTitle">Sueño</div><div class="fvZeppReviewGrid">'+
    input('fvZSleepDuration','Duración min',s.duration_min,'numeric')+input('fvZRegularity','Regularidad %',s.regularity_pct,'numeric')+input('fvZDeepMin','Profunda min',s.deep_min,'numeric')+input('fvZDeepPct','Profunda %',s.deep_pct,'numeric')+input('fvZRemMin','REM min',s.rem_min,'numeric')+input('fvZRemPct','REM %',s.rem_pct,'numeric')+input('fvZAwakeMin','Despierto min',s.awake_min,'numeric')+input('fvZAwakeCount','Despertares',s.awake_count,'numeric')+'</div>';
    if(notes.length){html+='<div class="fvZeppNotes">'+notes.map(function(x){return esc(x)}).join('<br>')+'</div>'}html+='<button class="actionbtn primary wide" style="margin-top:14px" id="fvZeppSave">Confirmar y guardar</button>';openSheet(html);var save=document.getElementById('fvZeppSave');if(save){save.onclick=saveReview}}
  function v(id){var e=document.getElementById(id),t=e?String(e.value||'').replace(/^\s+|\s+$/g,''):'';if(!t){return null}var n=Number(t.replace(',','.'));return isFinite(n)?n:null}
  function saveReview(){var b=document.getElementById('fvZeppSave');if(!b){return}b.disabled=true;b.textContent='Guardando…';var payload={activity:{steps:v('fvZSteps'),distance_km:v('fvZDistance'),activity_kcal:v('fvZActivityKcal'),resting_kcal:v('fvZRestingKcal'),total_kcal:v('fvZTotalKcal'),pai_total:v('fvZPaiTotal'),pai_today:v('fvZPaiToday')},sleep:{duration_min:v('fvZSleepDuration'),regularity_pct:v('fvZRegularity'),deep_min:v('fvZDeepMin'),deep_pct:v('fvZDeepPct'),rem_min:v('fvZRemMin'),rem_pct:v('fvZRemPct'),awake_min:v('fvZAwakeMin'),awake_count:v('fvZAwakeCount')}};request('zepp_save',payload).then(function(d){state.activityFile=null;state.sleepFile=null;state.review=null;closeSheet();cache({date:d.date,summary:d.summary,sleep:d.sleep});refreshCard();notify('Zepp guardado');haptic()}).catch(function(e){b.disabled=false;b.textContent='Confirmar y guardar';notify(friendlyError(e))})}
  function summaryHtml(d){var a=d&&d.summary?d.summary:null,s=d&&d.sleep?d.sleep:null;if(!a&&!s){return ''}return '<div class="fvZeppSummary" id="fvZeppSummary"><div class="fvZeppSummaryHead">Zepp</div><div class="fvZeppSummaryGrid"><div><small>Pasos</small><b>'+(a&&a.steps!=null?esc(a.steps):'—')+'</b></div><div><small>Actividad</small><b>'+(a&&a.activity_kcal!=null?esc(a.activity_kcal)+' kcal':'—')+'</b></div><div><small>PAI</small><b>'+(a&&a.pai_total!=null?esc(a.pai_total):'—')+'</b></div><div><small>Sueño</small><b>'+(s?esc(duration(s.duration_min)):'—')+'</b></div></div></div>'}
  function patchSummary(){var sheet=document.getElementById('sheet');if(!sheet||document.getElementById('fvZeppSummary')){return}var tx=String(sheet.textContent||'').toUpperCase();if(tx.indexOf('RESUMEN DEL DÍA')<0){return}var d=state.today;if(!d){loadToday().then(function(){patchSummary()});return}var html=summaryHtml(d);if(!html){return}var pending=sheet.querySelector('.fvPending'),finish=document.getElementById('fvConfirmFinish'),closed=sheet.querySelector('.fvDayClosed'),ref=pending||finish||closed;if(ref){var wrap=document.createElement('div');wrap.innerHTML=html;ref.parentNode.insertBefore(wrap.firstChild,ref)}else{sheet.insertAdjacentHTML('beforeend',html)}}
  function installObservers(){var home=document.getElementById('home'),sheet=document.getElementById('sheet');if(home&&window.MutationObserver){new MutationObserver(function(){renderCard()}).observe(home,{childList:true,subtree:true})}if(sheet&&window.MutationObserver){new MutationObserver(function(){patchSummary()}).observe(sheet,{childList:true,subtree:true})}}
  function install(){renderCard();installObservers();loadToday().then(function(){refreshCard();patchSummary()})}
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',install)}else{install()}
})();
